### PR TITLE
[WIP] Parse BGP Path Attributes

### PR DESCRIPTION
**Pull request by i7i**
[WIP] Parse the BGP Path Attributes found in the RIB Entries

### CODE REVIEW

**Comment by DevQps** [comment]
Hey i7i,

Are you still working on this? There is also the bgp-rs crate that can be used to parse the BGP messages. See https://github.com/DevQps/bgp-rs/

**Comment by DevQps** [comment]
Since https://github.com/DevQps/bgp-rs/ already provides this functionality in a better way I will close this PR.

**Comment by i7i** [comment]
@DevQps apologies. Have been sick and afk for the past couple weeks. Does bgp-rs parse AS path attributes that are in TABLE_DUMP_V2 records? I messed with bgp-rs and could not get it to pick up that record type. Could definitely be an error on my end.

**Comment by DevQps** [comment]
Hey sorry for the late reply! I hope you're feeling better in meanwhile! You're right btw! TABLE_DUMP_V2 only contains BGP path attributes and not complete messages so I think that currently bgp-rs does not support that yet. We're currently working on merging a new PR which should greatly enhance the functionality. I will also add an option that will allow for parsing path attributes directly! bgp-rs already contains tons of path attributes so I think it's best if we could just reuse that code as well!

For now I will create an issue for that on bgp-rs and implement it as soon as the PR lands!

**Comment by DevQps** [comment]
Hey @i7i 

There is a PR for it now!:

https://github.com/DevQps/bgp-rs/pull/37

If you see the /tests folder of bgp-rs and check the ripe.rs file you can already see the example live in the latest version of bgp-rs

**Pull request closed without merging**
